services:
        solver:
                image: "coar:latest"
                tty: true
                stdin_open: true
                volumes:
                        - type: bind
                          source: ..
                          target: /root/coar/script
                        - type: bind
                          source: ../../benchmarks
                          target: /root/coar/benchmarks
